import React from 'react'
import { Link } from 'react-router-dom'

const featureCards = [
  {
    title: 'Prompt-to-image flow',
    description: 'Compose, queue, and review full-resolution image generations from one studio surface instead of hopping between mock screens.',
  },
  {
    title: 'Private credit-backed gallery',
    description: 'Every completed job lands in your account history and gallery so you can actually manage outputs after they render.',
  },
  {
    title: 'GPU-first backend path',
    description: 'Imagyn is wired to FastAPI plus ComfyUI, with queue awareness and real job states instead of fake canvas placeholders.',
  },
]

export default function Landing({ systemStatus, modelCount = 0 }) {
  const comfyOnline = systemStatus?.comfyui_online

  return (
    <section className="space-y-8">
      <div className="hero-panel grid gap-8 xl:grid-cols-[1.25fr_0.95fr]">
        <div className="space-y-6">
          <p className="eyebrow">Editorial AI workspace</p>
          <div className="space-y-5">
            <h1 className="hero-title">
              Build images in a studio that looks intentional, not autogenerated.
            </h1>
            <p className="hero-copy">
              Imagyn pairs a real account system, generation history, gallery management, and a ComfyUI rendering pipeline into one polished surface for daily work.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <Link to="/login" className="primary-button">
              Create account
            </Link>
            <Link to="/" className="secondary-button">
              Explore the studio
            </Link>
          </div>

          <div className="grid gap-4 sm:grid-cols-3">
            <div className="stat-tile">
              <div className="stat-tile__value">{modelCount || 2}</div>
              <div className="stat-tile__label">models surfaced</div>
            </div>
            <div className="stat-tile">
              <div className="stat-tile__value">{comfyOnline ? 'GPU live' : 'Backend ready'}</div>
              <div className="stat-tile__label">render status</div>
            </div>
            <div className="stat-tile">
              <div className="stat-tile__value">100</div>
              <div className="stat-tile__label">starter credits</div>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <div className="surface-card h-full min-h-[360px] overflow-hidden">
            <div className="flex items-center justify-between border-b border-[var(--border-soft)] pb-4">
              <div>
                <p className="eyebrow">System signal</p>
                <h2 className="text-2xl font-semibold text-[var(--text-strong)]">Launch status</h2>
              </div>
              <span className={`status-dot ${comfyOnline ? 'status-dot--good' : 'status-dot--warm'}`} />
            </div>

            <div className="mt-6 grid gap-4">
              <div className="detail-row">
                <span>Backend API</span>
                <strong>{systemStatus?.backend || 'online'}</strong>
              </div>
              <div className="detail-row">
                <span>ComfyUI link</span>
                <strong>{comfyOnline ? 'Connected' : 'Checking GPU path'}</strong>
              </div>
              <div className="detail-row">
                <span>Default model</span>
                <strong>{systemStatus?.default_model || 'DreamShaper'}</strong>
              </div>
            </div>

            <div className="mt-8 rounded-[2rem] border border-[var(--border-soft)] bg-[var(--panel-muted)] p-5">
              <p className="eyebrow">Why it feels different</p>
              <p className="mt-3 text-sm leading-7 text-[var(--text-soft)]">
                The rebuilt experience focuses on editorial spacing, warm materials, clear state feedback, and a dual light-dark system so the product feels designed instead of assembled.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        {featureCards.map((card, index) => (
          <article key={card.title} className="surface-card reveal-card" style={{ animationDelay: `${index * 120}ms` }}>
            <p className="eyebrow">Feature {index + 1}</p>
            <h3 className="mt-3 text-2xl font-semibold text-[var(--text-strong)]">{card.title}</h3>
            <p className="mt-4 text-sm leading-7 text-[var(--text-soft)]">{card.description}</p>
          </article>
        ))}
      </div>
    </section>
  )
}
