// generate.js
// Try to call ComfyUI if configured; otherwise create a client-side canvas placeholder image
import { uploadDataUrlToSupabase } from './storage'

function uid() {
  return Math.random().toString(36).slice(2, 9)
}

function canvasPlaceholderDataUrl(prompt = '') {
  const width = 1024
  const height = 1024
  const canvas = Object.assign(document.createElement('canvas'), { width, height })
  const ctx = canvas.getContext('2d')

  // background gradient
  const g = ctx.createLinearGradient(0, 0, width, height)
  g.addColorStop(0, '#0ea5a4')
  g.addColorStop(0.5, '#7c3aed')
  g.addColorStop(1, '#ef4444')
  ctx.fillStyle = g
  ctx.fillRect(0, 0, width, height)

  // center card
  ctx.fillStyle = 'rgba(0,0,0,0.25)'
  ctx.fillRect(60, 60, width - 120, height - 120)

  // prompt text
  ctx.fillStyle = 'rgba(255,255,255,0.92)'
  ctx.font = '28px Inter, Arial'
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'

  const lines = wrapText(ctx, prompt || 'Generated by Imagyn (fallback)', width - 240)
  const startY = height / 2 - (lines.length * 18)
  lines.forEach((line, i) => ctx.fillText(line, width / 2, startY + i * 36))

  // small watermark
  ctx.font = '14px Inter, Arial'
  ctx.fillStyle = 'rgba(255,255,255,0.6)'
  ctx.fillText('Imagyn — fallback image', width - 160, height - 40)

  return canvas.toDataURL('image/png')
}

function wrapText(ctx, text, maxWidth) {
  const words = text.split(' ')
  const lines = []
  let current = ''
  for (let w of words) {
    const test = current ? `${current} ${w}` : w
    const m = ctx.measureText(test).width
    if (m > maxWidth && current) {
      lines.push(current)
      current = w
    } else {
      current = test
    }
  }
  if (current) lines.push(current)
  return lines
}

export async function generateImage({ prompt = '', model = '' } = {}) {
  const comfy = import.meta.env.VITE_COMFYUI_URL
  if (comfy) {
    try {
      // Try calling a standard generate endpoint; ComfyUI API varies across setups.
      const resp = await fetch(`${comfy.replace(/\/$/, '')}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, model })
      })
      if (resp.ok) {
        const json = await resp.json()
        // Expecting an image URL or base64 image. Try common shapes
        if (json.image_url) return { id: uid(), url: json.image_url, prompt }
        if (json.image_base64) return { id: uid(), url: `data:image/png;base64,${json.image_base64}`, prompt }
        // If unexpected, fallthrough to fallback
      }
    } catch (e) {
      console.warn('ComfyUI call failed, using fallback', e)
    }
  }

  // fallback: client-side placeholder image
  const url = canvasPlaceholderDataUrl(prompt)
  // If Supabase is configured, attempt to upload the generated data URL and return the public URL
  try {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
    const supabaseAnon = import.meta.env.VITE_SUPABASE_ANON_KEY
    if (supabaseUrl && supabaseAnon) {
      const publicUrl = await uploadDataUrlToSupabase(url)
      if (publicUrl) {
        return { id: uid(), url: publicUrl, prompt }
      }
    }
  } catch (e) {
    console.warn('Supabase upload failed, returning local data URL', e)
  }
  return { id: uid(), url, prompt }
}
